---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app1
spec:
  selector:
    matchLabels:
      name: app1
  replicas: 1
  template:
    metadata:
      labels:
        name: app1
    spec:
      containers:
      - name: app1
        image: httpd
